name: pumpfun-scrape-hourly

on:
  schedule:
    - cron: '0 * * * *'   # Runs every hour
  workflow_dispatch:       # Manual trigger

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run Pump.fun scraper
        env:
          TOKEN_ADDRESS: ${{ secrets.TOKEN_ADDRESS }}
        run: node index.js
